# predict/train_tft_model.py
#
# Bulletproof TFT training script for Bloodhound VC / ScoutIQ
# Auto-generates data if missing, patches import paths, runs safe on GitHub Actions

import os
import sys
import pandas as pd

# --- Patch for relative imports if running standalone or in GitHub Actions ---
root_path = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
if root_path not in sys.path:
    sys.path.insert(0, root_path)

# --- Ensure __init__.py exists in 'predict' for package import ---
init_path = os.path.join(root_path, "predict", "__init__.py")
if not os.path.exists(init_path):
    with open(init_path, "w") as f:
        f.write("# Autogenerated for package support\n")

from lightning.pytorch import Trainer
from lightning.pytorch.callbacks import EarlyStopping
from pytorch_forecasting import TimeSeriesDataSet, TemporalFusionTransformer
from pytorch_forecasting.metrics import QuantileLoss
from torch.utils.data import DataLoader
from predict.prepare_tft_data import prepare_timeseries_data

# --- Config ---
DATA_PATH = "artifacts/timeseries_data.parquet"
MAX_EPOCHS = 10
BATCH_SIZE = 64
TIME_IDX = "time_idx"
TARGET = "star_count"
GROUP_ID = "series_id"

def train_tft_model():
    print("🚀 Starting TFT model training...")

    # Step 1: Ensure data is present
    if not os.path.exists(DATA_PATH):
        print(f"📥 {DATA_PATH} not found. Running data preparation...")
        prepare_timeseries_data()

    print(f"📥 Loading data from {DATA_PATH}...")
    df = pd.read_parquet(DATA_PATH)
    df[TARGET] = df[TARGET].astype("float32")

    # Step 2: Build TimeSeriesDataSet
    print("📦 Creating TimeSeriesDataSet for training...")
    training = TimeSeriesDataSet(
        df,
        time_idx=TIME_IDX,
        target=TARGET,
        group_ids=[GROUP_ID],
        max_encoder_length=30,
        max_prediction_length=7,
        time_varying_known_reals=[TIME_IDX],
        time_varying_unknown_reals=[TARGET],
    )

    validation = TimeSeriesDataSet.from_dataset(training, df, predict=True, stop_randomization=True)

    train_dataloader = training.to_dataloader(train=True, batch_size=BATCH_SIZE, num_workers=0)
    val_dataloader = validation.to_dataloader(train=False, batch_size=BATCH_SIZE, num_workers=0)

    # Step 3: Model Config
    print("⚙️ Configuring TemporalFusionTransformer model...")
    model = TemporalFusionTransformer.from_dataset(
        training,
        learning_rate=0.03,
        hidden_size=16,
        attention_head_size=1,
        dropout=0.1,
        loss=QuantileLoss(),
        log_interval=10,
        reduce_on_plateau_patience=4,
    )

    # Step 4: Trainer
    print("🎯 Starting training...")
    trainer = Trainer(
        max_epochs=MAX_EPOCHS,
        accelerator="cpu",
        logger=False,
        callbacks=[EarlyStopping(monitor="val_loss", patience=3)],
    )

    trainer.fit(model, train_dataloaders=train_dataloader, val_dataloaders=val_dataloader)
    print("✅ Training complete.")

if __name__ == "__main__":
    train_tft_model()
