import type { RadarPayload, RadarProgram } from "@/app/radar-types";

const seen = "2026-09-02T16:01:00.000Z";

function scoring(
  freshness: number,
  reward: number,
  inspectability: number,
  authorization: number,
  friction: number,
) {
  return {
    total: freshness + reward + inspectability + authorization + friction,
    breakdown: { freshness, reward, inspectability, authorization, friction },
  };
}

const adobeScore = scoring(24, 14, 22, 8, 4);
const alteraScore = scoring(18, 17, 14, 8, 7);
const filecoinScore = scoring(18, 19, 24, 10, 5);
const coinDeskScore = scoring(32, 10, 10, 14, 8);
const aikidoScore = scoring(14, 6, 10, 8, 8);
const intuitionScore = scoring(22, 22, 22, 10, 7);

const samples: RadarProgram[] = [
  {
    id: "seed-adobe-public",
    name: "Adobe Public",
    platform: "Intigriti",
    url: "https://www.intigriti.com/programs/adobe/adobepublic/detail",
    status: "open",
    paid: true,
    currency: "USD",
    minReward: 75,
    maxReward: 15000,
    safeHarbor: null,
    disclosureAllowed: null,
    sourceIds: ["intigriti"],
    sourceCode: true,
    repositoryCount: 1,
    targetCount: 31,
    tags: ["source-code", "ai/ml", "web", "mobile"],
    languages: ["php"],
    targets: [
      {
        key: "source-code:magento",
        type: "source-code",
        value: "Adobe Commerce and Magento Open Source",
        eligible: true,
        impact: "Tier 2",
        description: "Local Magento Open Source testing is explicitly available.",
      },
      {
        key: "web:acrobat",
        type: "web",
        value: "Acrobat Web and approved AI features",
        eligible: true,
        impact: "Tier 1",
      },
    ],
    firstSeenAt: "2026-08-17T00:00:00.000Z",
    lastSeenAt: seen,
    lastChangedAt: "2026-08-17T00:00:00.000Z",
    change: {
      type: "new_program",
      label: "New program",
      at: "2026-08-17T00:00:00.000Z",
    },
    score: adobeScore.total,
    scoreBreakdown: adobeScore.breakdown,
    reasons: [
      "Recently listed",
      "Includes locally testable open source",
      "Reward ceiling clears the configured floor",
    ],
    attentionPressure: "medium",
    sample: true,
  },
  {
    id: "seed-altera",
    name: "Altera",
    platform: "Intigriti",
    url: "https://www.intigriti.com/programs/altera/altera/detail",
    status: "open",
    paid: true,
    currency: "USD",
    minReward: 500,
    maxReward: 30000,
    safeHarbor: null,
    disclosureAllowed: null,
    sourceIds: ["intigriti"],
    sourceCode: false,
    repositoryCount: 0,
    targetCount: 5,
    tags: ["hardware", "firmware", "executable"],
    languages: ["c", "c++"],
    targets: [
      {
        key: "hardware:fpga",
        type: "hardware",
        value: "FPGA integrated-circuit hardware",
        eligible: true,
        impact: "Tier 1",
      },
      {
        key: "firmware:sdm",
        type: "firmware",
        value: "SDM firmware",
        eligible: true,
        impact: "Tier 1",
      },
    ],
    firstSeenAt: "2026-08-28T10:00:00.000Z",
    lastSeenAt: seen,
    lastChangedAt: "2026-09-01T18:00:00.000Z",
    change: {
      type: "scope_updated",
      label: "Scope changed",
      at: "2026-09-01T18:00:00.000Z",
      addedTargets: 1,
    },
    score: alteraScore.total,
    scoreBreakdown: alteraScore.breakdown,
    reasons: ["Small, specialist scope", "High reward ceiling", "Recent scope movement"],
    attentionPressure: "unknown",
    sample: true,
  },
  {
    id: "seed-filecoin",
    name: "Filecoin",
    platform: "Immunefi",
    url: "https://immunefi.com/bug-bounty/filecoin/",
    status: "open",
    paid: true,
    currency: "USD",
    minReward: null,
    maxReward: 50000,
    safeHarbor: "program-defined",
    disclosureAllowed: null,
    sourceIds: ["manual-immunefi"],
    sourceCode: true,
    repositoryCount: 3,
    targetCount: 8,
    tags: ["source-code", "blockchain", "infrastructure"],
    languages: ["go", "rust"],
    targets: [
      {
        key: "source-code:filecoin",
        type: "source-code",
        value: "Published Filecoin implementation repositories",
        eligible: true,
      },
    ],
    firstSeenAt: "2026-04-14T00:00:00.000Z",
    lastSeenAt: seen,
    lastChangedAt: "2026-09-01T00:00:00.000Z",
    change: {
      type: "scope_updated",
      label: "Updated yesterday",
      at: "2026-09-01T00:00:00.000Z",
    },
    score: filecoinScore.total,
    scoreBreakdown: filecoinScore.breakdown,
    reasons: ["Recently updated", "Runnable PoC required", "Inspectable Go and Rust code"],
    attentionPressure: "unknown",
    sample: true,
  },
  {
    id: "seed-coindesk-data",
    name: "CoinDesk Data API",
    platform: "Bugcrowd",
    url: "https://bugcrowd.com/engagements/CCData-mbb-og",
    status: "open",
    paid: true,
    currency: "USD",
    minReward: null,
    maxReward: 7500,
    safeHarbor: "full",
    disclosureAllowed: false,
    sourceIds: ["bugcrowd"],
    sourceCode: false,
    repositoryCount: 0,
    targetCount: 2,
    tags: ["api", "finance"],
    languages: [],
    targets: [
      {
        key: "api:data-api",
        type: "api",
        value: "data-api.coindesk.com",
        eligible: true,
      },
      {
        key: "api:tools-api",
        type: "api",
        value: "tools-api.cryptocompare.com",
        eligible: true,
      },
    ],
    firstSeenAt: "2026-08-26T12:00:00.000Z",
    lastSeenAt: seen,
    lastChangedAt: "2026-09-02T08:20:00.000Z",
    change: {
      type: "new_target",
      label: "Target added",
      at: "2026-09-02T08:20:00.000Z",
      addedTargets: 1,
    },
    score: coinDeskScore.total,
    scoreBreakdown: coinDeskScore.breakdown,
    reasons: ["Fresh eligible target", "Only two in-scope targets", "Full safe harbor recorded"],
    attentionPressure: "lower",
    sample: true,
  },
  {
    id: "seed-aikido",
    name: "Aikido Security",
    platform: "Intigriti",
    url: "https://www.intigriti.com/programs/aikido/aikido/detail",
    status: "open",
    paid: true,
    currency: "EUR",
    minReward: 50,
    maxReward: 2500,
    safeHarbor: null,
    disclosureAllowed: null,
    sourceIds: ["intigriti"],
    sourceCode: false,
    repositoryCount: 0,
    targetCount: 1,
    tags: ["api", "web", "security-tooling"],
    languages: [],
    targets: [
      {
        key: "web:aikido",
        type: "web",
        value: "app.aikido.dev and its public API",
        eligible: true,
        impact: "Tier 2",
      },
    ],
    firstSeenAt: "2026-08-21T09:00:00.000Z",
    lastSeenAt: seen,
    lastChangedAt: "2026-08-30T09:00:00.000Z",
    change: {
      type: "scope_updated",
      label: "Scope changed",
      at: "2026-08-30T09:00:00.000Z",
    },
    score: aikidoScore.total,
    scoreBreakdown: aikidoScore.breakdown,
    reasons: ["One-target scope", "Public API documentation", "Reward is confirmed"],
    attentionPressure: "medium",
    sample: true,
  },
  {
    id: "seed-intuition",
    name: "Intuition",
    platform: "Immunefi",
    url: "https://immunefi.com/bug-bounty/intuition/",
    status: "open",
    paid: true,
    currency: "USD",
    minReward: 1000,
    maxReward: 100000,
    safeHarbor: "program-defined",
    disclosureAllowed: null,
    sourceIds: ["manual-immunefi"],
    sourceCode: true,
    repositoryCount: 1,
    targetCount: 4,
    tags: ["source-code", "smart-contract", "blockchain"],
    languages: ["solidity"],
    targets: [
      {
        key: "smart-contract:intuition",
        type: "smart-contract",
        value: "Published Intuition smart contracts",
        eligible: true,
      },
    ],
    firstSeenAt: "2026-07-08T00:00:00.000Z",
    lastSeenAt: seen,
    lastChangedAt: "2026-08-29T14:00:00.000Z",
    change: {
      type: "reward_up",
      label: "Reward changed",
      at: "2026-08-29T14:00:00.000Z",
    },
    score: intuitionScore.total,
    scoreBreakdown: intuitionScore.breakdown,
    reasons: ["Reward movement detected", "Public Solidity scope", "Minimum reward clears $1,000"],
    attentionPressure: "unknown",
    sample: true,
  },
];

export const seedPayload: RadarPayload = {
  meta: {
    generatedAt: seen,
    mode: "seed",
    sourceCount: 4,
    healthySourceCount: 4,
    programCount: samples.length,
    targetCount: samples.reduce((sum, program) => sum + program.targetCount, 0),
    eventCount: 5,
    sources: [
      { id: "hackerone", label: "HackerOne", status: "seed", count: 0 },
      { id: "bugcrowd", label: "Bugcrowd", status: "seed", count: 1 },
      { id: "intigriti", label: "Intigriti", status: "seed", count: 3 },
      { id: "manual-immunefi", label: "Immunefi", status: "seed", count: 2 },
    ],
  },
  programs: samples,
  preferences: {
    reviewedPrograms: ["Decred", "Leather", "MetaMask", "OnRe", "Jito", "Google OSRVP"],
    minReward: 1000,
  },
};
