import type { RadarPayload, RadarProgram, Workflow } from "@/app/radar-types";

const now = "2026-09-03T00:00:00.000Z";

function sample(
  id: string,
  name: string,
  workflow: Workflow,
  ceiling: "HIGH" | "CRITICAL",
  evScore: number,
  reason: string,
  target: { type: string; value: string },
): RadarProgram {
  return {
    id,
    name,
    platform: "Preview",
    url: "https://example.com/security",
    status: "open",
    paid: true,
    currency: "USD",
    minReward: 500,
    maxReward: 20_000,
    safeHarbor: "verify-policy",
    disclosureAllowed: null,
    sourceIds: ["preview"],
    sourceCode: workflow.startsWith("static-source"),
    repositoryCount: workflow.startsWith("static-source") ? 1 : 0,
    targetCount: 1,
    tags: [workflow],
    languages: workflow.startsWith("static-source") ? ["typescript"] : [],
    targets: [{
      key: `${id}:target`,
      type: target.type,
      value: target.value,
      eligible: true,
      workflow,
      payableSeverityCeiling: ceiling,
      programFloorSeverity: "MEDIUM",
      hardeningIndex: workflow.startsWith("static-source") ? 22 : null,
      freshCodeIndex: workflow.startsWith("static-source") ? 72 : 20,
      knownIssueRisk: 0,
      pFindable: 0.62,
      pPayable: 1,
      pFirst: 0.36,
      effectiveReward: 20_000,
      rewardCap: 50_000,
      rewardCapped: false,
      evScore,
      traps: [],
      excludeReason: null,
      reason,
    }],
    firstSeenAt: now,
    lastSeenAt: now,
    lastChangedAt: now,
    change: { type: "new_target", label: "Target added", at: now, addedTargets: 1 },
    score: 50,
    scoreBreakdown: { freshness: 20, reward: 12, inspectability: 8, authorization: 8, friction: 2 },
    reasons: [reason],
    honestReason: reason,
    attentionPressure: "unknown",
    hardeningIndex: workflow.startsWith("static-source") ? 22 : null,
    freshCodeIndex: workflow.startsWith("static-source") ? 72 : 20,
    knownIssueRisk: 0,
    payableSeverityCeiling: ceiling,
    programFloorSeverity: "MEDIUM",
    programFloorSource: "preview",
    workflow,
    findableClass: workflow === "live-web" ? "account-takeover" : "source-review",
    pFindable: 0.62,
    pPayable: 1,
    pFirst: 0.36,
    effectiveReward: 20_000,
    rewardCap: 50_000,
    rewardCapped: false,
    evScore,
    traps: [],
    excludeReason: null,
    bestTargetKey: `${id}:target`,
    sample: true,
  };
}

const programs = [
  sample("preview-auth", "Live Account Link", "live-web", "CRITICAL", 4_460, "fresh scope + live web + ATO ceiling CRITICAL + low recorded crowd", { type: "web", value: "https://login.example.com/account-link" }),
  sample("preview-api", "Tenant Admin API", "live-api", "HIGH", 2_180, "live api + cross-tenant ceiling HIGH + low hardening signal", { type: "api", value: "https://api.example.com/v2/tenants" }),
  sample("preview-agent", "Support Agent", "ai-agent", "HIGH", 1_340, "fresh scope + ai agent + exfil/SSRF ceiling HIGH", { type: "web", value: "https://agent.example.com" }),
  sample("preview-source", "New Billing Module", "static-source", "HIGH", 980, "fresh code + static source + price/authz ceiling HIGH + 8 files added/90d", { type: "source-code", value: "https://github.com/example/new-billing" }),
];

export const seedPayload: RadarPayload = {
  meta: {
    generatedAt: now,
    mode: "seed",
    sourceCount: 0,
    healthySourceCount: 0,
    programCount: programs.length,
    targetCount: programs.length,
    eventCount: 0,
    rankedProgramCount: programs.length,
    excludedProgramCount: 0,
    repoEnrichment: { discovered: 1, attempted: 0, updated: 0, failed: 0, pending: 1 },
    policyEnrichment: { discovered: programs.length, attempted: 0, updated: 0, failed: 0, pending: programs.length },
    sources: [],
  },
  programs,
  preferences: { reviewedPrograms: [], minReward: 1_000 },
};
